import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/mycomp/Footer";
import Header from "@/components/mycomp/Header";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header />
          <main className="mx-auto max-w-screen-2xl">{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
